apiVersion: 1

templates:
  - orgId: 1
    name: telegram.message
    template: |
      {{ define "telegram.message" }}
      {{ range .Alerts }}
      {{ if eq .Status "firing" }}🔴 FIRING{{ else }}✅ RESOLVED{{ end }} — {{ .Labels.alertname }}
      {{ .Annotations.summary }}
      {{ end }}
      {{ end }}
