---
version: "2.1"
services:
  manager:
    image: local/${manager_name}
    container_name: ${manager_name}
    network_mode: host
    restart: unless-stopped
    mem_limit: 512m
    depends_on:
      - db
    environment:
        DB_HOST: ${db_host}
        DB_PORT: ${db_port}
        DB_USER: ${db_user}
        DB_PASSWORD: ${db_password}
        PARSER_HOST: ${parser_host}
        PARSER_PORT: ${parser_port}
        SERVER_PORT: ${manager_port}
        TZ: Europe/Warsaw
  db:
    image: postgres
    container_name: ${db_name}
    network_mode: bridge
    restart: unless-stopped
    ports:
      - ${db_port}:5432
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - ${db_volume}:/var/lib/postgresql/data
volumes:
  ${db_volume}:
    external: true
networks:
  bridge:
    external: true
  host:
    external: true