apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    # host networking: Prometheus is reachable on localhost from this container
    url: http://localhost:9090
    isDefault: true
    editable: true
