---
version: "2.1"
services:
  parser:
    image: local/auction-page-parser
    container_name: auction-page-parser
    network_mode: host
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - 8081:8080
    depends_on:
      - chrome
    environment:
        CHROME_HOST: localhost
        CHROME_PORT: 4445
        SE_NODE_MAX_SESSIONS: 2
        SERVER_PORT: 8090
        TZ: Europe/Warsaw
  chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: test-chromium-for-parser
    network_mode: bridge
    ports:
      - 4445:4444
      - 7901:7900
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - VNC_NO_PASSWORD=1
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2g
    restart: unless-stopped
networks:
  host:
    external: true